INSERT INTO EMPLOYEE (ID, AGE, DESC, NAME, PASSWORD, ROLE_ROLE_ID ) VALUES ('1', 21, 'student', 'husiyang', '123456', '1');

INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES ('1','admin');

INSERT INTO MENU (MENU_ID, URL) VALUES ('1','/user');

INSERT INTO ROLE_EMPLOYEES (ROLE_ROLE_ID, EMPLOYEES_ID) VALUES ('1','1');

INSERT INTO ROLE_MENUS (ROLE_ROLE_ID, MENUS_MENU_ID) VALUES ('1','1');