server:
  port: 8080
spring:
  application:
        name: demo
  datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:hsy
        username: root
        password: root
  jpa:
#        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
#                show_sql: false
#                session_factory:
#                    statement_inspector: com.threegorges.demo.config.JpaInterceptor
        show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/


logging:
  level:
    org:
      springframework:
        data: DEBUG
        security: DEBUG